docs: add info on how to use a specific config
AtomLinter/linter-markdown pull request #211
Opened 2019-02-27 16:07 UTC by oupala

Add information about how to install and use this package in different configurations.

2019-02-27 16:18 UTC, wooorm approved these changes
✨

2019-02-28 00:22 UTC, Arcanemagus requested changes
Here's a first pass review of this.

If you have trouble wrapping the lines Atom has a built in command to reflow selected text for you:
* `Autoflow: Reflow Selection` in the Command Palette
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd> on Windows/Linux

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +## standard install (default configuration)
```suggestion
## Standard Installation
```
Headers should always be capitalized, I'd also leave off the part about the configuration as it's described in detail below.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +Lint markdown files using [remark-lint][remark-lint] and the [linter][linter] package for atom.
```suggestion
Lint markdown files using [remark-lint][remark-lint] and the
[linter][linter] package for Atom.
```
I'd prefer the line splitting to be in there, it makes no difference when rendered but makes diffs _much_ nicer to view.

Also "atom" should be capitalized.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +To use this `linter-markdown` package for Atom, simply install the package using the Atom package manager. If there is no configuration found for **remark-lint**, this linter runs [remark-preset-lint
Please just add the sentence at the start, the rest is identical and should be left on individual lines.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +If you need a specific configuration for the package, there is 2 ways of installing this `linter-markdown` package: a system-wide way, and a folder-specific way.
🔥 How `linter-markdown` is installed doesn't change regardless of how the extensions for `markdown` are installed.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +## folder-specific install (project-specific configuration)
This should be listed before the global instructions, project specific ones are _always_ preferred as they should be committed to the repository and shared by anyone working on it.

Global installations are a last resort that should virtually never actually be used.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +A similar linter, [linter-remark][], runs all remark plugins, but only when they are configured to run.
Again, please don't undo the line breaks.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +## folder-specific install (project-specific configuration)
```suggestion
## Project-specific Configuration
```
Let's emphasize that this is related to the configuration, not the method of installation of the plugins. This also has nothing to do with how `linter-markdown` itself is installed so I don't really like the word "install" in the header here as it could confuse people.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +You then have to locally install all modules referenced in your `.remarkrc` file, alongside `remark` and `remark-cli` (`npm install` without the `-g` or `--global` flag). If you do install modules gl
```suggestion
You then have to locally install all modules referenced in your `.remarkrc`
file, alongside `remark` and `remark-cli` (`npm install` without the `-g` or
`--global` flag).
```
The removed part is only relevant for a global installation.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +See [this tutorial][set-up] on how to set-up npm to work without sudo, which is good practise, and comes with the added benefit that `linter-markdown` can pick up on globally installed modules.
```suggestion
See [this tutorial][set-up] on how to set-up `npm` to work without `sudo`, which
is good practice, and comes with the added benefit that `linter-markdown` can
pick up on globally installed modules.
```
Misspelling of "practise" -> "practice" and no wrapping.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +## other informations
```suggestion
## More Information
```

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +## system-wide install (system-wide configuration)
```suggestion
## Global Configuration
```
This entire section should be de-emphasized below the project specific configuration.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +The system-wide way of installing the `linter-markdown` package should be used if you use the same configuration on all your markdown documents. This solution is also convenient if your markdown docu
```suggestion
The global configuration should only be used if you need to use the same
configuration on all your Markdown documents, and they aren't contained within
projects of their own.
```
Global configurations are virtually never the right solution, they should only be used if:
* The files aren't in projects **and**
* The files will _never_ be worked on by anyone else (even if the "other person" is yourself later on in the future)

And as stated before this has nothing to do with how `linter-markdown` itself is installed.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +You can set you system-wide configuration in a `.remarkrc` file that should be saved in `~/.remarkrc`, at the root of your home directory.
```suggestion
You can set you system-wide configuration in a `.remarkrc` file that should be
saved in `~/.remarkrc`, at the root of your home directory.
```

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +You then have to globally install all modules referenced in your `.remarkrc` file, alongside `remark` and `remark-cli` (`npm install` with the `-g` or `--global` flag).
```suggestion
You then have to globally install all modules referenced in your `.remarkrc`
file, alongside `remark` and `remark-cli` (`npm install` with the `-g` or
`--global` flag).
```

The line break between this sentence and the last should probably also be removed.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +The folder-specific way of installing the `linter-markdown` package should be used if you use differents configurations depending of each markdown document. This solution is also convenient if your m
```suggestion
The folder-specific way of configuring `remark` should be used if:
* You are working on the project with other people
* You need repeatable results
* You use need a different configuration for each project
```

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +You can set you folder-specific configuration in a `.remarkrc` file that should be saved in each folder of your markdown documents.
```suggestion
You can set you folder-specific configuration in:
* A `remarkConfig` section in `package.json`
* A `.remarkrc.js` or `.remarkrc` file
These should be placed in your project, see
[remark configuration](https://github.com/unifiedjs/unified-engine/blob/master/doc/configure.md)
for details.
```
The link there can probably be put down with the other links.

2019-02-28 00:22 UTC, Arcanemagus commented on README.md
> +If there *is* configuration for **remark-lint**, through `.remarkrc` files or `remarkConfig` in `package.json`s, this linter works just like [remark-cli][cli].
```suggestion
If there *is* configuration for **remark-lint**, through `.remarkrc` files or
`remarkConfig` in `package.json`s, this linter works just like
[remark-cli][cli].
```

2019-02-28 10:19 UTC, oupala commented on README.md
> +## folder-specific install (project-specific configuration)
Ok, fixed.

2019-02-28 10:20 UTC, oupala commented on README.md
> +To use this `linter-markdown` package for Atom, simply install the package using the Atom package manager. If there is no configuration found for **remark-lint**, this linter runs [remark-preset-lint
Ok, fixed.

2019-02-28 10:27 UTC, oupala commented on README.md
> +If you need a specific configuration for the package, there is 2 ways of installing this `linter-markdown` package: a system-wide way, and a folder-specific way.
I changed nothing because I don't understand what to do...

2019-02-28 10:28 UTC, oupala commented on README.md
> +A similar linter, [linter-remark][], runs all remark plugins, but only when they are configured to run.
Ok, fixed.

2019-03-06 16:39 UTC, oupala commented
@Arcanemagus I've put a lot of effort in this pull request (created from a previous one). I also changed pretty all what you asked to change. Could you please tell me if this pull request is mergeable or not?

2019-03-22 09:56 UTC, oupala commented
@Arcanemagus I had to update the pull request one more time. Could you please merge this pull request or tell me what should be improved?

2019-04-01 20:47 UTC, oupala commented
I'm a bit desperate about this pull request.

Should it be **that** hard to contribute to a *bit* of documentation?

2019-12-18 17:32 UTC, oupala commented
It seems so hard to contribute.

Have I missed something?

2020-02-14 16:12 UTC, oupala commented
Review requested for @Arcanemagus.

2020-03-20 17:03 UTC, oupala commented
@Arcanemagus Would you mind reviewing this merge request? Thanks.

2022-01-07 20:40 UTC, closed without merging